---
- name: create namespace
  command: "{{ dest_folder }}/local-kafka-setup/createNamespace.sh"

- name: build and start kafka
  command: "{{ dest_folder }}/local-kafka-setup/startKafka.sh"

- name: build and start mssql-centos
  command: "{{ dest_folder }}/mssql-centos/startContainer.sh"

- name: build and start party
  command: "{{ dest_folder }}/party-service/build-run.sh"

- name: build and start passenger
  command: "{{ dest_folder }}/passenger/build-run.sh"

- name: build and start route-service
  command: "{{ dest_folder }}/route-service/build-run.sh"

- name: build and start query-service
  command: "{{ dest_folder }}/query-service/build-run.sh"

- name: build party-ui
  command: "{{ dest_folder }}/party-ui/buildAndPushImage.sh"

- name: start party-ui
  command: "{{ dest_folder }}/party-ui/startContainer.sh"